### ISSUE TITLE
Running on CPU NameError: free variable 'valid_label' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by alaizag** [HubertTang/RdRpBin#6]
Hi,

I am trying to run RdRpBin on example/test.fasta on a server (no GPU) and getting the following error:

```
Traceback (most recent call last):
  File "main.py", line 298, in <module>
    run_on_real(args = rdrpbin_args,
  File "main.py", line 277, in run_on_real
    motif_gcn_utils.train_motif_GCN(args=args,
  File "/localdisk/home/s2420489/rdrpbin/RdRpBin/motif_gcn_utils.py", line 156, in train_motif_GCN
    val_loss, val_acc = evaluate()
  File "/localdisk/home/s2420489/rdrpbin/RdRpBin/motif_gcn_utils.py", line 118, in evaluate
    eval_loss = masked_loss(eval_out, valid_label, valid_mask, class_weights)
NameError: free variable 'valid_label' referenced before assignment in enclosing scope
```
What I did was to set CUDA_VISIBLE_DEVICES in the environment to null to avoid "RuntimeError: CUDA out of memory" which was showing up before. So, the command is 
```
export CUDA_VISIBLE_DEVICES=""
python main.py -t 8 example/test.fasta
```
Thanks

**Comment by HubertTang** [comment]
Hi there,

I just add an option `--force_cpu` to run the model using CPU only. You can run using the following commands:

`python main.py -t 8 --force_cpu True example/test.fasta`

I hope this helps! Let me know if you have any further questions.

**Comment by alaizag** [comment]
That works now, many thanks! I still need to assign the variable though when using the --force_cpu option.
